version: '2'

services:

  nfsen:
    build: nfsen-ng
    environment:
      TZ: "Europe/Warsaw"
    ports:
    - 80:80
    volumes:
    - ./profiles-data:/var/nfdump/profiles-data
    - ./sources.conf:/tmp/sources.conf:ro
    restart: always
    
  nfdump:
    build: nfdump
    environment:
      TZ: "Europe/Warsaw"    
    ports:
    - 2055:2055/udp
    volumes:
    - ./profiles-data:/data
    - ./sources.conf:/tmp/sources.conf:ro
    restart: always
